models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/player/uboa2/uboa2.bmp
models/player/uboa2/uboa2.mdl
models/player/uboa2b/uboa2b.bmp
models/player/uboa2b/uboa2b.mdl
models/prturi4/agentgrunt.mdl
models/prturi4/sam.mdl
models/REvil/Archvile.mdl
models/turr/scicotic.mdl
models/uboa/babygarg.mdl
models/uboa/babygargt.mdl
models/uboa/bigmassn.mdl
models/uboa/bluedragon.mdl
models/uboa/bluemassn.mdl
models/uboa/civilian.mdl
models/uboa/g_bigmassn.mdl
models/uboa/gamesaba.mdl
models/uboa/gamesabat.mdl
models/uboa/garg.mdl
models/uboa/gargt.mdl
models/uboa/greendragon.mdl
models/uboa/greenmassn.mdl
models/uboa/greymassn.mdl
models/uboa/gyudon.mdl
models/uboa/headcrab.mdl
models/uboa/kanateko.mdl
models/uboa/kintama.mdl
models/uboa/kintamat.mdl
models/uboa/matsutake.mdl
models/uboa/mrkimo.mdl
models/uboa/mrkimot.mdl
models/uboa/owner.mdl
models/uboa/redmassn.mdl
models/uboa/scimassn.mdl
models/uboa/scimassnf.mdl
models/uboa/table.mdl
models/uboa/usagim.mdl
models/uboa/usagir.mdl
models/uboa/wrench.mdl
models/uboa/yellowmassn.mdl
sound/uboa/dragonsmarch.wav
sound/uboa/gj.wav
sound/uboa/gonorego.wav
sound/uboa/iyaaa.wav
sound/uboa/moedra.wav
sound/uboa/onani.wav
sound/uboa/rainforce.wav
sound/uboa/warning.wav
sound/uboa/yattana.wav
sound/votemap/finish.wav
sound/votemap/hakasemix.wav
sound/votemap/juon.wav
sound/votemap/moisdead.wav
sprites/votemap/chopper_ride.spr
sprites/votemap/halflifuro.spr
sprites/votemap/heli_small.spr
sprites/votemap/reco.spr
sprites/votemap/rhapsody.spr
sprites/votemap/sc_fortress.spr
sprites/votemap/sc_sniperwar_xmas.spr
sprites/votemap/skillgauss.spr
sprites/votemap/uplink.spr
