gfx/env/enkai_bk.tga
gfx/env/enkai_dn.tga
gfx/env/enkai_ft.tga
gfx/env/enkai_lf.tga
gfx/env/enkai_rt.tga
gfx/env/enkai_up.tga
gfx/env/enkaid_bk.tga
gfx/env/enkaid_dn.tga
gfx/env/enkaid_ft.tga
gfx/env/enkaid_lf.tga
gfx/env/enkaid_rt.tga
gfx/env/enkaid_up.tga
maps/kani_gyosen.bsp
maps/kani_gyosen.cfg
maps/kani_gyosen_motd.txt
models/kani_gyosen/hata.mdl
models/kani_gyosen/kujira.mdl
models/kani_gyosen/models.txt
models/kani_gyosen/p_aps.mdl
models/kani_gyosen/p_bgrap.mdl
models/kani_gyosen/p_harpoon.mdl
models/kani_gyosen/p_harpoon2.mdl
models/kani_gyosen/p_medkit.mdl
models/kani_gyosen/v_aps.mdl
models/kani_gyosen/v_bgrap.mdl
models/kani_gyosen/v_harpoon.mdl
models/kani_gyosen/v_medkit.mdl
models/kani_gyosen/w_aps.mdl
models/kani_gyosen/w_bgrap.mdl
models/kani_gyosen/w_harpoon.mdl
models/kani_gyosen/w_kanikama.mdl
models/kani_gyosen/w_kanikan.mdl
models/kani_gyosen/w_pmedkit.mdl
sound/kani_gyosen/clearing1.ogg
sound/kani_gyosen/end.ogg
sound/kani_gyosen/umi.wav
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
sprites/kani_gyosen/get.spr
sprites/kani_gyosen/hokaku.spr
sprites/kani_gyosen/ui1.spr
sprites/kani_gyosen/weapon_aps.txt
sprites/kani_gyosen/weapon_harpoon.txt
