// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/reco/Archvile.mdl
models/reco/biggator.mdl
models/reco/crimson.mdl
models/reco/dead2.mdl
models/reco/furnature/butch_dead.mdl
models/reco/furnature/vat_charlie.mdl
models/reco/girl1.mdl
models/reco/gonome.mdl
models/reco/gorger.mdl
models/reco/gorgert.mdl
models/reco/hunter.mdl
models/reco/imodels/allied_ammo.mdl
models/reco/imodels/brownshield.mdl
models/reco/imodels/goldshield.mdl
models/reco/imodels/resource_cd.mdl
models/reco/imodels/ring.mdl
models/reco/imodels/w_isotopebox.mdl
models/reco/imodels/w_kevlar.mdl
models/reco/imodels/w_security.mdl
models/reco/imodels/xen_folder2.mdl
models/reco/licker.mdl
models/reco/neptune.mdl
models/reco/neptunet.mdl
models/reco/reaver.mdl
models/reco/sci.mdl
models/reco/security.mdl
models/reco/specialops.mdl
models/reco/statue1.mdl
models/reco/superlicker.mdl
models/reco/wmodels/357/v_357.mdl
models/reco/wmodels/beretta/v_9mmhandgun.mdl
models/reco/wmodels/chainsaw/p_chainsaw.mdl
models/reco/wmodels/chainsaw/v_chainsaw.mdl
models/reco/wmodels/chainsaw/w_chainsaw.mdl
models/reco/wmodels/grapgun/p_grap.mdl
models/reco/wmodels/grapgun/v_grap.mdl
models/reco/wmodels/grapgun/w_grap.mdl
models/reco/wmodels/knife/p_crowbar.mdl
models/reco/wmodels/knife/v_crowbar.mdl
models/reco/wmodels/knife/w_crowbar.mdl
models/reco/wmodels/m3/p_shotgun.mdl
models/reco/wmodels/m3/v_shotgun.mdl
models/reco/wmodels/m3/w_shotgun.mdl
models/reco/wmodels/m4/p_9mmar.mdl
models/reco/wmodels/m4/v_9mmar.mdl
models/reco/wmodels/m4/w_9mmar.mdl
models/reco/wmodels/m40a1/v_m40a1.mdl
models/reco/wmodels/medkit/v_medkit.mdl
models/reco/wmodels/minigun/v_minigun.mdl
models/reco/wmodels/scout/p_crossbow.mdl
models/reco/wmodels/scout/v_crossbow.mdl
models/reco/wmodels/scout/w_crossbow.mdl
models/reco/wmodels/usp9mmauto/p_uzi.mdl
models/reco/wmodels/usp9mmauto/v_uzi.mdl
models/reco/wmodels/usp9mmauto/w_uzi.mdl
models/reco/xscientist.mdl
models/reco/zombie.mdl
sound/hostage/hos6.wav
sound/hostage/hos7.wav
sound/hunter/alert.wav
sound/hunter/die.wav
sound/hunter/hit.wav
sound/hunter/pain.wav
sound/revil/bossbattle2.wav
sound/revil/cricket.wav
sound/revil/escapealarm.wav
sound/revil/heartbeat.wav
sound/revil/lookout.wav
sound/revil/morph.wav
sound/revil/newscream2.wav
sound/revil/re2music1.wav
sound/revil/residentevil.wav
sound/revil/rjigalo.wav
sound/revil/scaryass.wav
sound/revil/suppliez.wav
sound/revil/umbrellalab.wav
sound/revil/voxescapemessage.wav
sound/revil/zombie_attack.wav
sound/revil/zombieburst2.wav
sound/rezombie/claw_miss1.wav
sound/rezombie/claw_miss2.wav
sound/rezombie/claw_strike1.wav
sound/rezombie/claw_strike2.wav
sound/rezombie/claw_strike3.wav
sound/rezombie/zo_alert10.wav
sound/rezombie/zo_alert20.wav
sound/rezombie/zo_alert30.wav
sound/rezombie/zo_attack1.wav
sound/rezombie/zo_attack2.wav
sound/rezombie/zo_idle1.wav
sound/rezombie/zo_idle2.wav
sound/rezombie/zo_idle3.wav
sound/rezombie/zo_idle4.wav
sound/rezombie/zo_pain1.wav
sound/rezombie/zo_pain2.wav
sound/tyrant/primalscreaming.wav
sound/tyrant/role4_idle1.wav
sound/tyrant/role4_idle2.wav
sound/tyrant/role4_idle3.wav
sound/tyrant/role7_die2.wav
sound/tyrant/role7_die3.wav
sound/tyrant/role7_die4.wav
sound/tyrant/role7_spawn1.wav
sound/tyrant/role7_wound1.wav
sound/weapons/chainsaw_start.wav
sound/weapons/scout_bolt.wav
sound/weapons/scout_clipin.wav
sound/weapons/scout_clipout.wav
