maps/uboa_rampage.bsp
maps/uboa_rampage.cfg
maps/uboa_rampage_motd.txt
maps/uboa_rampage_skl.cfg
models/player/uboac/uboa_color.txt
models/player/uboac/uboac.bmp
models/player/uboac/uboac.mdl
models/uboa_rampage/akikan.mdl
models/uboa_rampage/hagesaba.mdl
models/uboa_rampage/hagesabaT.mdl
models/uboa_rampage/ichybarney.mdl
models/uboa_rampage/ichybarney_boss.mdl
models/uboa_rampage/ichybarney_bossT.mdl
models/uboa_rampage/ichybarneyT.mdl
models/uboa_rampage/ichyhakase.mdl
models/uboa_rampage/ichyhakase_boss.mdl
models/uboa_rampage/ichyhakase_bossT.mdl
models/uboa_rampage/ichyhakaseT.mdl
models/uboa_rampage/imomushi.mdl
models/uboa_rampage/imomushi_boss.mdl
models/uboa_rampage/imomushi_mini.mdl
models/uboa_rampage/konichiwa.mdl
models/uboa_rampage/models.txt
models/uboa_rampage/morimaki_melee.mdl
models/uboa_rampage/morimaki_meleeT.mdl
models/uboa_rampage/moripo.mdl
models/uboa_rampage/mrkimo.mdl
models/uboa_rampage/mrkimo_boss.mdl
models/uboa_rampage/mrkimo_bossT.mdl
models/uboa_rampage/mrkimot.mdl
models/uboa_rampage/nnmad.mdl
models/uboa_rampage/nnmad_kintama.mdl
models/uboa_rampage/nnmad_kintamaT.mdl
models/uboa_rampage/p_bat.mdl
models/uboa_rampage/p_bokutou.mdl
models/uboa_rampage/p_brush.mdl
models/uboa_rampage/p_fryingpan.mdl
models/uboa_rampage/p_goldbar.mdl
models/uboa_rampage/p_hockeystick.mdl
models/uboa_rampage/p_ironpipe.mdl
models/uboa_rampage/p_kakuzai.mdl
models/uboa_rampage/p_medkit.mdl
models/uboa_rampage/p_merikensack.mdl
models/uboa_rampage/p_metalbat.mdl
models/uboa_rampage/p_monkeywrench.mdl
models/uboa_rampage/p_nailbat.mdl
models/uboa_rampage/p_platinumbar.mdl
models/uboa_rampage/p_shinai.mdl
models/uboa_rampage/p_shovel.mdl
models/uboa_rampage/p_tennisracket.mdl
models/uboa_rampage/pi_tree.mdl
models/uboa_rampage/ripoD.mdl
models/uboa_rampage/sake.mdl
models/uboa_rampage/sincube.mdl
models/uboa_rampage/uboazombie.mdl
models/uboa_rampage/uboazombie_boss.mdl
models/uboa_rampage/uboazombie_boss01.mdl
models/uboa_rampage/uboazombie_boss02.mdl
models/uboa_rampage/uboazombie_boss03.mdl
models/uboa_rampage/uboazombie_bossT.mdl
models/uboa_rampage/uboazombie01.mdl
models/uboa_rampage/uboazombie02.mdl
models/uboa_rampage/uboazombie03.mdl
models/uboa_rampage/uboazombieT.mdl
models/uboa_rampage/v_bat.mdl
models/uboa_rampage/v_bokutou.mdl
models/uboa_rampage/v_brush.mdl
models/uboa_rampage/v_fryingpan.mdl
models/uboa_rampage/v_goldbar.mdl
models/uboa_rampage/v_hockeystick.mdl
models/uboa_rampage/v_ironpipe.mdl
models/uboa_rampage/v_kakuzai.mdl
models/uboa_rampage/v_medkit.mdl
models/uboa_rampage/v_merikensack.mdl
models/uboa_rampage/v_metalbat.mdl
models/uboa_rampage/v_monkeywrench.mdl
models/uboa_rampage/v_nailbat.mdl
models/uboa_rampage/v_platinumbar.mdl
models/uboa_rampage/v_shinai.mdl
models/uboa_rampage/v_shovel.mdl
models/uboa_rampage/v_tennisracket.mdl
models/uboa_rampage/w_bat.mdl
models/uboa_rampage/w_bokutou.mdl
models/uboa_rampage/w_brush.mdl
models/uboa_rampage/w_fryingpan.mdl
models/uboa_rampage/w_goldbar.mdl
models/uboa_rampage/w_hockeystick.mdl
models/uboa_rampage/w_ironpipe.mdl
models/uboa_rampage/w_kakuzai.mdl
models/uboa_rampage/w_merikensack.mdl
models/uboa_rampage/w_metalbat.mdl
models/uboa_rampage/w_monkeywrench.mdl
models/uboa_rampage/w_nailbat.mdl
models/uboa_rampage/w_platinumbar.mdl
models/uboa_rampage/w_pmedkit.mdl
models/uboa_rampage/w_shinai.mdl
models/uboa_rampage/w_shovel.mdl
models/uboa_rampage/w_tennisracket.mdl
models/uboa45/gamern.mdl
sound/takedeppo/50cal_fire.wav
sound/takedeppo/50cal_fun_time.wav
sound/uboa_rampage/acoustic38.ogg
sound/uboa_rampage/babygarg.txt
sound/uboa_rampage/bahhh.wav
sound/uboa_rampage/bishi.wav
sound/uboa_rampage/dareda.wav
sound/uboa_rampage/doka.wav
sound/uboa_rampage/ichybarney.txt
sound/uboa_rampage/ichyhakase.txt
sound/uboa_rampage/imomushi.txt
sound/uboa_rampage/imomushi_sq.txt
sound/uboa_rampage/kichigai.wav
sound/uboa_rampage/konichiwa.txt
sound/uboa_rampage/koraa.wav
sound/uboa_rampage/moripo.txt
sound/uboa_rampage/neorock60.ogg
sound/uboa_rampage/neorock66.ogg
sound/uboa_rampage/neorock68.ogg
sound/uboa_rampage/neorock70.ogg
sound/uboa_rampage/neorock79_loop.ogg
sound/uboa_rampage/nnmad.txt
sound/uboa_rampage/sounds.txt
sound/uboa_rampage/sunaa.wav
sound/uboa_rampage/uboa_h.wav
sound/uboa_rampage/uboazombie.txt
sound/uboa_rampage/uwaaa_h.wav
sound/uboa_rampage/waaa.wav
sound/uboa/ichybarney/ichy_alert1.wav
sound/uboa/ichybarney/ichy_alert2.wav
sound/uboa/ichybarney/ichy_alert3.wav
sound/uboa/ichybarney/ichy_attack1.wav
sound/uboa/ichybarney/ichy_attack2.wav
sound/uboa/ichybarney/ichy_bite1.wav
sound/uboa/ichybarney/ichy_bite2.wav
sound/uboa/ichybarney/ichy_die1.wav
sound/uboa/ichybarney/ichy_die2.wav
sound/uboa/ichybarney/ichy_die3.wav
sound/uboa/ichybarney/ichy_die4.wav
sound/uboa/ichybarney/ichy_idle1.wav
sound/uboa/ichybarney/ichy_idle2.wav
sound/uboa/ichybarney/ichy_idle3.wav
sound/uboa/ichybarney/ichy_idle4.wav
sound/uboa/ichybarney/ichy_pain1.wav
sound/uboa/ichybarney/ichy_pain2.wav
sound/uboa/ichybarney/ichy_pain3.wav
sound/uboa/ichybarney/ichy_pain4.wav
sound/uboa/ichybarney/ichy_pain5.wav
sound/uboa/ichyhakase/ichy_alert1.wav
sound/uboa/ichyhakase/ichy_alert2.wav
sound/uboa/ichyhakase/ichy_alert3.wav
sound/uboa/ichyhakase/ichy_attack1.wav
sound/uboa/ichyhakase/ichy_attack2.wav
sound/uboa/ichyhakase/ichy_bite1.wav
sound/uboa/ichyhakase/ichy_bite2.wav
sound/uboa/ichyhakase/ichy_die1.wav
sound/uboa/ichyhakase/ichy_die2.wav
sound/uboa/ichyhakase/ichy_die3.wav
sound/uboa/ichyhakase/ichy_die4.wav
sound/uboa/ichyhakase/ichy_idle1.wav
sound/uboa/ichyhakase/ichy_idle2.wav
sound/uboa/ichyhakase/ichy_idle3.wav
sound/uboa/ichyhakase/ichy_idle4.wav
sound/uboa/ichyhakase/ichy_pain1.wav
sound/uboa/ichyhakase/ichy_pain2.wav
sound/uboa/ichyhakase/ichy_pain3.wav
sound/uboa/ichyhakase/ichy_pain4.wav
sound/uboa/ichyhakase/ichy_pain5.wav
sound/uboa/konichiwa/attack.wav
sound/uboa/konichiwa/konichiwa.wav
sound/uboa/konichiwa/konichiwa2.wav
sound/uboa/konichiwa/konichiwa3.wav
sound/uboa/konichiwa/miss.wav
sound/uboa/moripo/ara.wav
sound/uboa/moripo/ara2.wav
sound/uboa/moripo/ara3.wav
sound/uboa/uboazombie/zo_pain1.wav
sound/uboa/uboazombie/zo_pain2.wav
sound/uboa45/bgm_loop.wav
sound/uboa45/bgm_start.wav
sprites/uboa_rampage/ammoicon.spr
sprites/uboa_rampage/uboa_weapon1.spr
sprites/uboa_rampage/uboa_weapon2.spr
sprites/uboa_rampage/uboa_weapon3.spr
sprites/uboa_rampage/uboa_weapon4.spr
sprites/uboa_rampage/uboa_weapon5.spr
sprites/uboa_rampage/uboa_weapon6.spr
sprites/uboa_rampage/uboa_weapon7.spr
sprites/uboa_rampage/uboa_weapon8.spr
sprites/uboa_rampage/weapon_bat.txt
sprites/uboa_rampage/weapon_bokutou.txt
sprites/uboa_rampage/weapon_brush.txt
sprites/uboa_rampage/weapon_fryingpan.txt
sprites/uboa_rampage/weapon_goldbar.txt
sprites/uboa_rampage/weapon_hockeystick.txt
sprites/uboa_rampage/weapon_ironpipe.txt
sprites/uboa_rampage/weapon_kakuzai.txt
sprites/uboa_rampage/weapon_merikensack.txt
sprites/uboa_rampage/weapon_metalbat.txt
sprites/uboa_rampage/weapon_monkeywrench.txt
sprites/uboa_rampage/weapon_nailbat.txt
sprites/uboa_rampage/weapon_platinumbar.txt
sprites/uboa_rampage/weapon_shinai.txt
sprites/uboa_rampage/weapon_shovel.txt
sprites/uboa_rampage/weapon_tennisracket.txt
